[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
    
[build]
  functions = "netlify/functions"

# Add cache control headers for the cache function
[[headers]]
  for = "/.netlify/functions/cache"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Cache-Control = "public, max-age=600" # 10 minutes client-side cache