export const notableCreators = [
  { id: 5111, name: "Hideaki Anno", about: "Creator of Evangelion" },
  { id: 1870, name: "Hayao Miyazaki", about: "Co-founder of Studio Ghibli" },
  { id: 1891, name: "Yoshihiro Togashi", about: "Creator of Hunter x Hunter" },
  { id: 1881, name: "Eiichiro Oda", about: "Creator of One Piece" },
  { id: 1879, name: "Masashi Kishimoto", about: "Creator of Naruto" },
  { id: 1901, name: "Akira Toriyama", about: "Creator of Dragon Ball" },
  { id: 1880, name: "Tite Kubo", about: "Creator of Bleach" },
  { id: 1868, name: "Kentaro Miura", about: "Creator of Berserk" },
  { id: 1892, name: "Rumiko Takahashi", about: "Creator of InuYasha" },
  { id: 1886, name: "Tsugumi Ohba", about: "Creator of Death Note" },
  { id: 1887, name: "Takeshi Obata", about: "Artist of Death Note" },
  { id: 2619, name: "Hirohiko Araki", about: "Creator of JoJo's Bizarre Adventure" },
  { id: 2128, name: "Naoko Takeuchi", about: "Creator of Sailor Moon" },
  { id: 1874, name: "Hiromu Arakawa", about: "Creator of Fullmetal Alchemist" },
  { id: 10308, name: "Gen Urobuchi", about: "Creator of Madoka Magica, Fate/Zero" },
  { id: 2009, name: "Shinichiro Watanabe", about: "Director of Cowboy Bebop" },
  { id: 1117, name: "Makoto Shinkai", about: "Creator of Your Name" },
  { id: 4580, name: "Satoshi Kon", about: "Director of Perfect Blue" },
  { id: 1867, name: "Osamu Tezuka", about: "Creator of Astro Boy" },
  { id: 2192, name: "Go Nagai", about: "Creator of Mazinger Z" }
];

export const majorStudios = [
  { id: 1, name: "Sunrise", about: "Known for Gundam series" },
  { id: 2, name: "Kyoto Animation", about: "Known for K-On!, Violet Evergarden" },
  { id: 4, name: "Bones", about: "Known for My Hero Academia" },
  { id: 7, name: "J.C.Staff", about: "Known for Toradora!" },
  { id: 11, name: "Madhouse", about: "Known for Death Note, One Punch Man S1" },
  { id: 14, name: "Toei Animation", about: "Known for Dragon Ball, One Piece" },
  { id: 17, name: "ufotable", about: "Known for Demon Slayer" },
  { id: 21, name: "Studio Ghibli", about: "Known for Spirited Away" },
  { id: 43, name: "Production I.G", about: "Known for Ghost in the Shell" },
  { id: 44, name: "Shaft", about: "Known for Monogatari Series" },
  { id: 53, name: "A-1 Pictures", about: "Known for Sword Art Online" },
  { id: 287, name: "David Production", about: "Known for JoJo's Bizarre Adventure" },
  { id: 456, name: "MAPPA", about: "Known for Jujutsu Kaisen" },
  { id: 858, name: "White Fox", about: "Known for Steins;Gate, Re:Zero" },
  { id: 803, name: "Trigger", about: "Known for Kill la Kill" },
  { id: 1835, name: "Studio WIT", about: "Known for Attack on Titan S1-S3" },
  { id: 569, name: "SILVER LINK.", about: "Known for Non Non Biyori" },
  { id: 291, name: "Brain's Base", about: "Known for Durarara!!" },
  { id: 121, name: "Sunrise", about: "Known for Code Geass" },
  { id: 73, name: "P.A. Works", about: "Known for Angel Beats!" }
];
